# Generated by Django 5.0.7 on 2024-08-02 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrawl', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(0, 'Poem'), (1, 'Lyrics'), (2, 'Excerpt'), (3, 'Drabble')], max_length=1)),
                ('body', models.CharField(max_length=3000)),
                ('quills', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scrawls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
