# Generated by Django 5.0.7 on 2024-08-04 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrawl', '0003_alter_scrawl_quills_alter_scrawl_type_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scrawl',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
