# Generated by Django 5.0.7 on 2024-08-05 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrawl', '0004_scrawl_saved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrawl',
            name='quills',
        ),
        migrations.AlterField(
            model_name='scrawl',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_scrawls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrawl',
            name='quills',
            field=models.ManyToManyField(blank=True, related_name='liked_scrawls', to=settings.AUTH_USER_MODEL),
        ),
    ]
