# Generated by Django 5.0.7 on 2024-08-05 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrawl', '0006_rename_quills_scrawl_liked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrawl',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='scrawl',
            name='quills',
            field=models.ManyToManyField(blank=True, related_name='quilled_scrawls', to=settings.AUTH_USER_MODEL),
        ),
    ]
