# Generated by Django 5.0.7 on 2024-08-05 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrawl', '0007_remove_scrawl_liked_by_scrawl_quills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scrawl',
            name='quilled_by',
            field=models.ManyToManyField(blank=True, related_name='quilled_scrawls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='scrawl',
            name='quills',
        ),
        migrations.AddField(
            model_name='scrawl',
            name='quills',
            field=models.IntegerField(default=0),
        ),
    ]
