# Generated by Django 5.0.7 on 2024-08-05 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrawl', '0008_scrawl_quilled_by_remove_scrawl_quills_scrawl_quills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='quilled_by',
            field=models.ManyToManyField(blank=True, related_name='quilled_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
